products:
  - url: https://www.runnmore.com/patike/69807049-adidas-patike-adizero-adios-pro-4
    name: 'Adidas Adizero Adios Pro 4'
  - url: https://trebapatike.rs/sr/hoka-mach-7
    name: 'HOKA Mach 7'
