products:
  - url: https://www.gigatron.rs/slusalice/sony-wh-1000xm5-bele
    name: 'Sony WH-1000XM5'
  # - url: https://www.amazon.de/dp/B09GMN9SL5
  #   name: "Kindle Paperwhite"
  # - url: https://www.mediamarkt.at/de/product/some-product.html
  #   name: "Some Product"
